export const GAMES = [
  { title:"Madden NFL 27", date:[2026,7,13], platforms:['ps','xbox','switch','pc'], genre:"Sports" },
  { title:"Hell Let Loose: Vietnam", date:[2026,7,13], platforms:['ps','xbox','pc'], genre:"Tactical Shooter" },
  { title:"Ground Zero Hero", date:[2026,7,20], platforms:['ps','xbox','switch','pc'], genre:"Action" },
  { title:"Grave Seasons", date:[2026,7,14], platforms:['ps','xbox','switch','pc'], genre:"Adventure" },
  { title:"The Witch's Bakery", date:[2026,7,20], platforms:['ps','xbox','switch','pc'], genre:"Simulation" },
  { title:"Metal Gear Solid Master Collection Vol. 2", date:[2026,7,27], platforms:['ps','xbox','switch','pc'], genre:"Action-Adventure", desc:"A collection bringing more entries from Konami's stealth-action series to modern platforms." },
  { title:"Star Wars: Zero Company", date:[2026,7,27], platforms:['ps','xbox','pc'], genre:"Tactics", desc:"A turn-based tactics game set in the Star Wars universe from the creators of Mutant Year Zero." },
  { title:"Aggelos 2", date:[2026,7,27], platforms:['ps','xbox','switch','pc'], genre:"Action-Adventure" },
  { title:"Resonance: A Plague Tale Legacy", date:[2026,7,27], platforms:['ps','xbox','pc'], genre:"Action-Adventure", desc:"A story-driven continuation of the A Plague Tale series' blend of stealth and survival.", steam:{ price:39.99, deck:'verified' } },
  { title:"Serious Sam: Shatterverse", date:[2026,7,31], platforms:['ps','xbox','pc'], genre:"FPS", steam:{ price:29.99, deck:'playable' } },
  { title:"The Blood of Dawnwalker", date:[2026,8,3], platforms:['ps','xbox','pc'], genre:"Action RPG", desc:"An open-world action RPG about a reluctant vampire balancing humanity and hunger across a single in-game week.", steam:{ price:59.99, deck:'playable' } },
  { title:"Onimusha: Way of the Sword", date:[2026,8,4], platforms:['ps','xbox','switch','pc'], genre:"Hack and Slash", desc:"A return to Capcom's samurai action series, blending swordplay with supernatural enemies.", steam:{ price:49.99, deck:'verified' } },
  { title:"Valheim", date:[2026,8,9], platforms:['ps','xbox','switch','pc'], genre:"Survival", desc:"A cooperative survival game set in a procedurally generated, Norse-inspired purgatory.", steam:{ price:19.99, discountPrice:9.99, discountPct:50, deck:'verified' } },
  { title:"Marvel's Wolverine", date:[2026,8,15], platforms:['ps'], genre:"Action-Adventure", desc:"A single-player action-adventure from Insomniac Games centered on Marvel's clawed antihero." },
  { title:"Fire Emblem: Fortune's Weave", date:[2026,8,17], platforms:['switch'], genre:"Tactical RPG", desc:"A tactical RPG entry in Nintendo's long-running Fire Emblem strategy series." },
  { title:"Silent Hill: Townfall", date:[2026,8,24], platforms:['ps','pc'], genre:"Survival Horror", desc:"A survival horror game set in the fog-shrouded world of Silent Hill.", steam:{ price:69.99, deck:'unsupported' } },
  { title:"Harvest Moon: Echoes of Teradea", date:[2026,8,24], platforms:['ps','xbox','switch','pc'], genre:"Farming Sim", desc:"A farming and life-sim adventure in the long-running Harvest Moon series.", steam:{ price:39.99, deck:'verified' } },
  { title:"Moonlighter 2", date:[2026,8,2], platforms:['ps','xbox','switch','pc'], genre:"Action RPG", desc:"A sequel blending dungeon-crawling combat with running your own shop between runs." },
  { title:"Orbitals", date:[2026,8,3], platforms:['switch'], genre:"Puzzle" },
  { title:"Hot Wheels: Infinite Rush", date:[2026,8,10], platforms:['ps','xbox','switch','pc'], genre:"Racing" },
  { title:"Endless Legend 2", date:[2026,8,17], platforms:['ps','xbox','pc'], genre:"4X Strategy", desc:"A 4X strategy sequel set in the fantasy Endless universe.", steam:{ price:44.99, deck:'playable' } },
  { title:"Trails in the Sky 2nd Chapter", date:[2026,8,17], platforms:['ps','switch','pc'], genre:"JRPG", desc:"A continuation of the beloved Trails JRPG series' Sky story arc.", steam:{ price:34.99, deck:'verified' } },
  { title:"The Grinch 2: Saving Christmas", date:[2026,8,18], platforms:['ps','xbox','switch','pc'], genre:"Platformer" },
  { title:"Control Resonant", date:[2026,8,24], platforms:['ps','xbox','pc'], genre:"Action-Adventure", desc:"An action-adventure spin-off set in the supernatural world of Remedy's Control.", steam:{ price:59.99, deck:'playable' } },
  { title:"Garfield – Escape From Monday", date:[2026,8,24], platforms:['ps','xbox','switch','pc'], genre:"Platformer" },
  { title:"Gears of War: E-Day", date:[2026,9,6], platforms:['xbox','pc'], genre:"Third-Person Shooter", desc:"A prequel to the Gears of War series, depicting the outbreak that started the Locust War.", steam:{ price:59.99, deck:'playable' } },
  { title:"Kingdom Hearts Collection I–III", date:[2026,9,8], platforms:['ps','xbox','switch'], genre:"Action RPG", desc:"A compilation bringing early Kingdom Hearts entries to current-gen platforms." },
  { title:"Enshrouded", date:[2026,9,15], platforms:['ps','pc'], genre:"Survival RPG", desc:"A survival-action RPG set in a world overtaken by a mysterious, deadly fog.", steam:{ price:29.99, discountPrice:20.99, discountPct:30, deck:'verified' } },
  { title:"Nintendo Switch Sports Resort", date:[2026,9,22], platforms:['switch'], genre:"Party/Sports" },
  { title:"Call of Duty: Modern Warfare 4", date:[2026,9,23], platforms:['ps','xbox','switch','pc'], genre:"FPS" },
  { title:"Phantom Blade Zero", date:[2026,9,29], platforms:['ps','pc'], genre:"Action RPG", desc:"A stylish action RPG blending wuxia aesthetics with fast-paced combat.", steam:{ price:49.99, deck:'playable' } },
  { title:"Minecraft Dungeons 2", date:[2026,8,29], platforms:['ps','xbox','switch','pc'], genre:"Dungeon Crawler", desc:"A dungeon-crawler sequel set in the Minecraft universe." },
  { title:"TOEM 2", date:[2026,8,29], platforms:['ps','switch','pc'], genre:"Adventure", steam:{ price:16.99, deck:'verified' } },
  { title:"End of Abyss", date:[2026,9,1], platforms:['ps','xbox','pc'], genre:"Action RPG", steam:{ price:34.99, deck:'playable' } },
  { title:"Rayman Legends Retold", date:[2026,9,1], platforms:['ps','xbox','switch','pc'], genre:"Platformer", desc:"An updated take on the acclaimed platformer starring Rayman and friends." },
  { title:"Ace Combat 8: Wings of Theve", date:[2026,9,2], platforms:['ps','xbox','pc'], genre:"Flight Combat", desc:"The next entry in Bandai Namco's arcade flight combat series.", steam:{ price:69.99, deck:'unsupported' } },
  { title:"Star Wars: Galactic Racer", date:[2026,9,6], platforms:['ps','xbox','pc'], genre:"Racing" },
  { title:"Echo Weaver", date:[2026,9,8], platforms:['ps','xbox','switch','pc'], genre:"Adventure" },
  { title:"Silver Pines", date:[2026,9,8], platforms:['ps','xbox','switch','pc'], genre:"Horror" },
  { title:"Planet Zoo 2", date:[2026,9,13], platforms:['ps','xbox','pc'], genre:"Simulation", desc:"A zoo management sim sequel focused on animal care and habitat design.", steam:{ price:44.99, deck:'verified' } },
  { title:"Valor Mortis", date:[2026,9,13], platforms:['ps','xbox','pc'], genre:"Tactics" },
  { title:"Castlevania: Belmont's Curse", date:[2026,9,15], platforms:['ps','xbox','switch','pc'], genre:"Action-Adventure", desc:"An action-adventure entry in Konami's gothic vampire-hunting series." },
  { title:"Tales of Eternia Remastered", date:[2026,9,16], platforms:['ps','xbox','switch','pc'], genre:"JRPG", desc:"A remaster of the classic entry in Bandai Namco's Tales JRPG series." },
  { title:"Final Fantasy Resonance", date:[2026,9,22], platforms:['ps','xbox','switch','pc'], genre:"JRPG", desc:"A new entry exploring the Final Fantasy universe with an original story.", steam:{ price:69.99, deck:'playable' } },
  { title:"One Piece: Grand Gourmet", date:[2026,9,23], platforms:['switch','pc'], genre:"Party", steam:{ price:39.99, deck:'verified' } },
  { title:"Hello Kitty Party Land", date:[2026,9,29], platforms:['switch'], genre:"Party" },
  { title:"Barbie Rewind", date:[2026,10,12], platforms:['ps','xbox','switch','pc'], genre:"Adventure", steam:{ price:34.99, discountPrice:29.74, discountPct:15, deck:'unsupported' } },
  { title:"Grand Theft Auto 6", date:[2026,10,19], platforms:['ps','xbox'], genre:"Open World", desc:"Rockstar's next open-world crime saga, and its most anticipated release in years." },
  { title:"Godzilla: Destroy All Monsters Melee Remastered", date:[2026,10,3], platforms:['ps','xbox','switch','pc'], genre:"Fighting", desc:"A remaster of the GameCube-era brawler pitting kaiju against each other." },
  { title:"Dragon Quest Monsters: The Withered World", date:[2026,11,3], platforms:['ps','switch'], genre:"Monster-Taming RPG", desc:"A monster-taming RPG entry in the long-running Dragon Quest Monsters series." },
];
